//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommentManagement_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableComment
    {
        public int Id { get; set; }
        public string Post { get; set; }
        public string Admin { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> Dislike { get; set; }
    }
}
